export const USER_API_END_POINT = "http://localhost:8000/api/v1/users"
export const PROJECT_API_END_POINT = "http://localhost:8000/api/v1/projects"
export const TENANT_API_END_POINT = "http://localhost:8000/api/v1/tenants"
export const ACTIVITY_API_END_POINT = "http://localhost:8000/api/v1/activity"
export const PROJECT_MEMBER_API_END_POINT = "http://localhost:8000/api/v1/project-member"